=== jiargei/rnx-xml/copies.dtd
<!ELEMENT stations (station*)>
    <!ATTLIST stations xmlns:xsi CDATA #IMPLIED>
    <!ATTLIST stations xsi:noNamespaceSchemaLocation CDATA #IMPLIED>
<!ELEMENT station (year*)>
    <!ATTLIST station StationID ID #REQUIRED>
<!ELEMENT year (doys*)>
    <!ATTLIST year YearID CDATA #REQUIRED>
<!ELEMENT doys (#PCDATA)>
    <!ATTLIST doys processed CDATA #IMPLIED>

=== jiargei/rnx-xml/sample.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE stations SYSTEM "copies.dtd">
<stations 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="copies.xsd"
>
    <station StationID="ONSA">
    </station>
    <station StationID="GRAZ"/>
    <station StationID="PAKO">
        <year YearID="2016">
            <doys>105,106</doys>
        </year>
        <year YearID="2015"/>
    </station>
    <station StationID="WIEN">
        <year YearID="2015">
            <doys processed="1">178,180</doys>
            <doys>201,202</doys>
        </year>
        <year YearID="2016">
            <doys>178,180</doys>
            <doys>201,202</doys>
        </year>
    </station>
    <station StationID="TRBG">
        <year YearID="2016">
            <doys>178,180</doys>
            <doys>201,202</doys>
        </year>
    </station>
    <station StationID="PFAN">
        <year YearID="2016">
            <doys>178,180</doys>
            <doys>201,202</doys>
        </year>
    </station>
</stations>
